import Config

config :sanctum, google_redirect_uri: "https://sanctum.fly.dev/auth/user/google/callback"

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :sanctum, SanctumWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Sentry: errors, logs, and OTel-based tracing. The DSN (and release) are set
# at runtime from Fly secrets — see config/runtime.exs. Source-context options
# must live here (compile time) so `mix sentry.package_source_code` can read
# them during the Docker build.
config :sentry,
  environment_name: "production",
  enable_source_code_context: true,
  root_source_code_paths: [File.cwd!()],
  in_app_otp_apps: [:sanctum],
  integrations: [oban: [capture_errors: true, cron: [enabled: true]]],
  enable_logs: true,
  logs: [level: :info, metadata: [:request_id, :game_id, :user_id]],
  traces_sampler: {Sanctum.Observability, :traces_sampler}

# Route OTel spans into Sentry instead of an OTLP collector.
config :opentelemetry,
  span_processor: {Sentry.OpenTelemetry.SpanProcessor, []},
  sampler: {Sentry.OpenTelemetry.Sampler, []},
  text_map_propagators: [:trace_context, :baggage, Sentry.OpenTelemetry.Propagator]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
