defmodule Sanctum.Repo.Migrations.ModifyHeroAndSchemeToSupportSides do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:heroes) do
      add :base_code, :text
    end

    create unique_index(:heroes, [:base_code, :set], name: "heroes_unique_hero_set_index")

    alter table(:game_schemes) do
      add :active_side_id,
          references(:card_sides,
            column: :id,
            name: "game_schemes_active_side_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:game_cards) do
      add :active_side_id,
          references(:card_sides,
            column: :id,
            name: "game_cards_active_side_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:decks) do
      remove :alter_ego_code
      remove :hero_code

      add :hero_id,
          references(:heroes,
            column: :id,
            name: "decks_hero_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    alter table(:cards) do
      remove :image_url
      remove :boost_star
      remove :boost
      remove :max_threat
      remove :escalation_threat
      remove :base_threat
      remove :scheme
      remove :stage
      remove :health_per_hero
      remove :recover
      remove :hand_size
      remove :resource_wild_count
      remove :resource_mental_count
      remove :resource_physical_count
      remove :resource_energy_count
      remove :hazard_icon
      remove :crisis_icon
      remove :amplify_icon
      remove :acceleration_icon
      remove :cost
      remove :health
      remove :defense_cost
      remove :defense
      remove :thwart_cost
      remove :thwart
      remove :attack_cost
      remove :attack
      remove :text
      remove :aspect
      remove :type
      remove :traits
      remove :subname
      remove :name
      add :is_multi_sided, :boolean, default: false
      add :base_code, :text, null: false
    end

    create unique_index(:cards, [:base_code], name: "cards_unique_marvelcdb_base_code_index")
  end

  def down do
    drop_if_exists unique_index(:cards, [:base_code],
                     name: "cards_unique_marvelcdb_base_code_index"
                   )

    alter table(:cards) do
      remove :base_code
      remove :is_multi_sided
      add :name, :text, null: false
      add :subname, :text
      add :traits, {:array, :text}, default: []
      add :type, :text
      add :aspect, :text
      add :text, :text
      add :attack, :bigint
      add :attack_cost, :bigint
      add :thwart, :bigint
      add :thwart_cost, :bigint
      add :defense, :bigint
      add :defense_cost, :bigint
      add :health, :bigint
      add :cost, :bigint
      add :acceleration_icon, :boolean, default: false
      add :amplify_icon, :boolean, default: false
      add :crisis_icon, :boolean, default: false
      add :hazard_icon, :boolean, default: false
      add :resource_energy_count, :bigint
      add :resource_physical_count, :bigint
      add :resource_mental_count, :bigint
      add :resource_wild_count, :bigint
      add :hand_size, :bigint
      add :recover, :bigint
      add :health_per_hero, :boolean, default: false
      add :stage, :bigint
      add :scheme, :bigint
      add :base_threat, :bigint
      add :escalation_threat, :bigint
      add :max_threat, :bigint
      add :boost, :bigint
      add :boost_star, :boolean, default: false
      add :image_url, :text
    end

    drop constraint(:decks, "decks_hero_id_fkey")

    alter table(:decks) do
      remove :hero_id

      add :hero_code,
          references(:cards,
            column: :code,
            name: "decks_hero_code_fkey",
            type: :text,
            prefix: "public"
          ),
          null: false

      add :alter_ego_code,
          references(:cards,
            column: :code,
            name: "decks_alter_ego_code_fkey",
            type: :text,
            prefix: "public"
          ),
          null: false
    end

    drop constraint(:game_cards, "game_cards_active_side_id_fkey")

    alter table(:game_cards) do
      remove :active_side_id
    end

    drop constraint(:game_schemes, "game_schemes_active_side_id_fkey")

    alter table(:game_schemes) do
      remove :active_side_id
    end

    drop_if_exists unique_index(:heroes, [:base_code, :set], name: "heroes_unique_hero_set_index")

    alter table(:heroes) do
      remove :base_code
    end
  end
end
