defmodule Sanctum.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:cards) do
      remove :aspect
      remove :type
      remove :traits
      remove :subname
      remove :name
    end
  end

  def down do
    alter table(:cards) do
      add :name, :text, null: false
      add :subname, :text
      add :traits, {:array, :text}, default: []
      add :type, :text
      add :aspect, :text
    end
  end
end
