defmodule Sanctum.Repo.Migrations.AddUniqueIdentityForGamePlayers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:game_players, [:user_id, :game_id],
             name: "game_players_unique_game_id_user_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:game_players, [:user_id, :game_id],
                     name: "game_players_unique_game_id_user_id_index"
                   )
  end
end
