defmodule Sanctum.Repo.Migrations.AddRecommendedModSets do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:scenarios) do
      add :recommended_modular_sets, {:array, :text}, null: false
    end
  end

  def down do
    alter table(:scenarios) do
      remove :recommended_modular_sets
    end
  end
end
