defmodule Sanctum.Repo.Migrations.AddGamePlayers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:games) do
      remove :deck_id
      add :state, :text, null: false
      add :player_order, {:array, :text}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:game_players, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :form, :text
      add :health, :bigint
      add :max_health, :bigint
      add :hand_size, :bigint
      add :hand_size_mod, :bigint, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :game_id,
          references(:games,
            column: :id,
            name: "game_players_game_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :deck_id,
          references(:decks,
            column: :id,
            name: "game_players_deck_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:game_players, "game_players_game_id_fkey")

    drop constraint(:game_players, "game_players_deck_id_fkey")

    drop table(:game_players)

    alter table(:games) do
      remove :updated_at
      remove :inserted_at
      remove :player_order
      remove :state

      add :deck_id,
          references(:decks,
            column: :id,
            name: "games_deck_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end
end
