defmodule Sanctum.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:game_schemes) do
      modify :threat, :bigint, default: 0
    end
  end

  def down do
    alter table(:game_schemes) do
      modify :threat, :bigint, default: nil
    end
  end
end
