defmodule Sanctum.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:villains, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :villain_name, :text
      add :set, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:villains, [:villain_name, :set],
             name: "villains_unique_villain_set_index"
           )

    create table(:game_villains, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :health, :bigint
      add :max_health, :bigint
      add :attack, :bigint
      add :scheme, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :game_id,
          references(:games,
            column: :id,
            name: "game_villains_game_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :villain_id,
          references(:villains,
            column: :id,
            name: "game_villains_villain_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :active_stage_card_id,
          references(:cards,
            column: :id,
            name: "game_villains_active_stage_card_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :active_stage_side_id,
          references(:card_sides,
            column: :id,
            name: "game_villains_active_stage_side_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:game_villains, "game_villains_game_id_fkey")

    drop constraint(:game_villains, "game_villains_villain_id_fkey")

    drop constraint(:game_villains, "game_villains_active_stage_card_id_fkey")

    drop constraint(:game_villains, "game_villains_active_stage_side_id_fkey")

    drop table(:game_villains)

    drop_if_exists unique_index(:villains, [:villain_name, :set],
                     name: "villains_unique_villain_set_index"
                   )

    drop table(:villains)
  end
end
