defmodule Sanctum.Repo.Migrations.AddVillianToGame do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:games) do
      add :villian_id,
          references(:cards,
            column: :id,
            name: "games_villian_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:games, "games_villian_id_fkey")

    alter table(:games) do
      remove :villian_id
    end
  end
end
