defmodule Sanctum.Repo.Migrations.UpdateCardsWithMarvelcdbFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:cards) do
      add :code, :text
      add :pack_code, :text
      add :pack_name, :text
      add :real_name, :text
      add :subname, :text
      add :type_code, :text, null: false
      add :type_name, :text, null: false
      add :faction_code, :text, null: false
      add :faction_name, :text, null: false
      add :card_set_code, :text
      add :card_set_name, :text
      add :card_set_type_name_code, :text
      add :real_text, :text
      add :position, :bigint, null: false
      add :set_position, :bigint
      add :linked_to_code, :text
      add :linked_to_name, :text
      add :deck_limit, :bigint, null: false, default: 1
      add :resource_energy, :bigint, null: false, default: 0
      add :resource_physical, :bigint, null: false, default: 0
      add :resource_mental, :bigint, null: false, default: 0
      add :resource_wild, :bigint, null: false, default: 0
      add :boost, :bigint
      add :cost_per_hero, :boolean, null: false, default: false
      add :health_per_hero, :boolean, null: false, default: false
      add :thwart_cost, :bigint
      add :attack_cost, :bigint
      add :defense_cost, :bigint
      add :recover_cost, :bigint
      add :attack_star, :boolean, null: false, default: false
      add :thwart_star, :boolean, null: false, default: false
      add :defense_star, :boolean, null: false, default: false
      add :health_star, :boolean, null: false, default: false
      add :recover_star, :boolean, null: false, default: false
      add :scheme_star, :boolean, null: false, default: false
      add :boost_star, :boolean, null: false, default: false
      add :threat_star, :boolean, null: false, default: false
      add :escalation_threat_star, :boolean, null: false, default: false
      add :threat, :bigint
      add :threat_fixed, :boolean, null: false, default: false
      add :base_threat_fixed, :boolean, null: false, default: false
      add :escalation_threat_fixed, :boolean, null: false, default: false
      add :hidden, :boolean, null: false, default: false
      add :permanent, :boolean, null: false, default: false
      add :double_sided, :boolean, null: false, default: false
      add :octgn_id, :text
      add :url, :text
      add :imagesrc, :text
      add :illustrator, :text
      add :errata, :text
      add :spoiler, :bigint
      add :meta, :map
      add :back_text, :text
      add :back_flavor, :text
      add :back_name, :text
      add :backimagesrc, :text
    end

    create unique_index(:cards, [:pack_code, :position], name: "cards_unique_card_in_pack_index")

    create unique_index(:cards, [:code], name: "cards_unique_marvelcdb_code_index")
  end

  def down do
    drop_if_exists unique_index(:cards, [:code], name: "cards_unique_marvelcdb_code_index")

    drop_if_exists unique_index(:cards, [:pack_code, :position],
                     name: "cards_unique_card_in_pack_index"
                   )

    alter table(:cards) do
      remove :backimagesrc
      remove :back_name
      remove :back_flavor
      remove :back_text
      remove :meta
      remove :spoiler
      remove :errata
      remove :illustrator
      remove :imagesrc
      remove :url
      remove :octgn_id
      remove :double_sided
      remove :permanent
      remove :hidden
      remove :escalation_threat_fixed
      remove :base_threat_fixed
      remove :threat_fixed
      remove :threat
      remove :escalation_threat_star
      remove :threat_star
      remove :boost_star
      remove :scheme_star
      remove :recover_star
      remove :health_star
      remove :defense_star
      remove :thwart_star
      remove :attack_star
      remove :recover_cost
      remove :defense_cost
      remove :attack_cost
      remove :thwart_cost
      remove :health_per_hero
      remove :cost_per_hero
      remove :boost
      remove :resource_wild
      remove :resource_mental
      remove :resource_physical
      remove :resource_energy
      remove :deck_limit
      remove :linked_to_name
      remove :linked_to_code
      remove :set_position
      remove :position
      remove :real_text
      remove :card_set_type_name_code
      remove :card_set_name
      remove :card_set_code
      remove :faction_name
      remove :faction_code
      remove :type_name
      remove :type_code
      remove :subname
      remove :real_name
      remove :pack_name
      remove :pack_code
      remove :code
    end
  end
end
