defmodule Sanctum.Repo.Migrations.AddGameSchemes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:game_schemes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :threat, :bigint
      add :max_threat, :bigint
      add :escalation_threat, :bigint
      add :is_main_scheme, :boolean

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :game_id,
          references(:games,
            column: :id,
            name: "game_schemes_game_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :card_id,
          references(:cards,
            column: :id,
            name: "game_schemes_card_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:game_schemes, "game_schemes_game_id_fkey")

    drop constraint(:game_schemes, "game_schemes_card_id_fkey")

    drop table(:game_schemes)
  end
end
