defmodule Sanctum.Repo.Migrations.AddDeckScenarioAndModSetsToGame do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:games) do
      remove :main_scheme_id
      remove :villain_id
      remove :hero_id
      add :modular_sets, {:array, :text}, null: false

      add :deck_id,
          references(:decks,
            column: :id,
            name: "games_deck_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :scenario_id,
          references(:scenarios,
            column: :id,
            name: "games_scenario_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:games, "games_deck_id_fkey")

    drop constraint(:games, "games_scenario_id_fkey")

    alter table(:games) do
      remove :scenario_id
      remove :deck_id
      remove :modular_sets

      add :hero_id,
          references(:cards,
            column: :id,
            name: "games_hero_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :villain_id,
          references(:cards,
            column: :id,
            name: "games_villain_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :main_scheme_id,
          references(:cards,
            column: :id,
            name: "games_main_scheme_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end
end
