defmodule Sanctum.Repo.Migrations.AddEncounterDeck do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:game_encounter_decks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :game_id,
          references(:games,
            column: :id,
            name: "game_encounter_decks_game_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    alter table(:game_cards) do
      add :game_encounter_deck_id,
          references(:game_encounter_decks,
            column: :id,
            name: "game_cards_game_encounter_deck_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:game_cards, "game_cards_game_encounter_deck_id_fkey")

    alter table(:game_cards) do
      remove :game_encounter_deck_id
    end

    drop constraint(:game_encounter_decks, "game_encounter_decks_game_id_fkey")

    drop table(:game_encounter_decks)
  end
end
