defmodule Sanctum.Repo.Migrations.SetupBaseResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:cards, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :subname, :text
      add :traits, {:array, :text}
      add :type, :text
      add :aspect, :text
      add :text, :text
      add :attack, :bigint
      add :attack_cost, :bigint
      add :thwart, :bigint
      add :thwart_cost, :bigint
      add :defense, :bigint
      add :defense_cost, :bigint
      add :health, :bigint
      add :cost, :bigint
      add :deck_limit, :bigint
      add :unique, :boolean, default: false
      add :permanent, :boolean, default: false
      add :acceleration_icon, :boolean, default: false
      add :amplify_icon, :boolean, default: false
      add :crisis_icon, :boolean, default: false
      add :hazard_icon, :boolean, default: false
      add :resource_energy_count, :bigint
      add :resource_physical_count, :bigint
      add :resource_mental_count, :bigint
      add :resource_wild_count, :bigint
      add :hand_size, :bigint
      add :recover, :bigint
      add :health_per_hero, :bigint
      add :stage, :bigint
      add :base_threat, :bigint
      add :escalation_threat, :bigint
      add :boost, :bigint
      add :boost_star, :boolean, default: false
      add :card_set, :text
      add :code, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:cards, [:code], name: "cards_unique_marvelcdb_code_index")
  end

  def down do
    drop_if_exists unique_index(:cards, [:code], name: "cards_unique_marvelcdb_code_index")

    drop table(:cards)
  end
end
