defmodule Sanctum.Repo.Migrations.AddAlterEgoToDeck do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:decks) do
      add :alter_ego_code,
          references(:cards,
            column: :code,
            name: "decks_alter_ego_code_fkey",
            type: :text,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:decks, "decks_alter_ego_code_fkey")

    alter table(:decks) do
      remove :alter_ego_code
    end
  end
end
