defmodule Sanctum.Repo.Migrations.MigrateResources3 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:cards) do
      add :base_code, :text, null: false
    end

    create unique_index(:cards, [:base_code], name: "cards_unique_marvelcdb_base_code_index")
  end

  def down do
    drop_if_exists unique_index(:cards, [:base_code],
                     name: "cards_unique_marvelcdb_base_code_index"
                   )

    alter table(:cards) do
      remove :base_code
    end
  end
end
