defmodule Sanctum.Repo.Migrations.AssignGameCardsToGamePlayers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:game_cards) do
      remove :user_id
      remove :game_id

      add :game_player_id,
          references(:game_players,
            column: :id,
            name: "game_cards_game_player_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:game_cards, "game_cards_game_player_id_fkey")

    alter table(:game_cards) do
      remove :game_player_id

      add :game_id,
          references(:games,
            column: :id,
            name: "game_cards_game_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :user_id,
          references(:users,
            column: :id,
            name: "game_cards_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end
end
