defmodule Sanctum.Repo.Migrations.AddSchemeToCard do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:cards) do
      add :scheme, :bigint
    end
  end

  def down do
    alter table(:cards) do
      remove :scheme
    end
  end
end
