defmodule Sanctum.Repo.Migrations.AddCounterToGameSchemes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:game_schemes) do
      add :counter, :bigint, default: 0
    end
  end

  def down do
    alter table(:game_schemes) do
      remove :counter
    end
  end
end
