defmodule Sanctum.Repo.Migrations.SetDefaultHeroForm do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:game_players) do
      modify :form, :text, default: "alter_ego"
    end
  end

  def down do
    alter table(:game_players) do
      modify :form, :text, default: nil
    end
  end
end
