defmodule Sanctum.Repo.Migrations.AddSetAndNameToModularSet do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:modular_sets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :set_code, :text, null: false
    end

    create unique_index(:modular_sets, [:set_code], name: "modular_sets_set_code_index")
  end

  def down do
    drop_if_exists unique_index(:modular_sets, [:set_code], name: "modular_sets_set_code_index")

    drop table(:modular_sets)
  end
end
