defmodule Sanctum.Repo.Migrations.AddGameCards do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:game_cards, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :zone, :text, null: false
      add :order, :bigint, null: false
      add :status, :text, default: "ready"
      add :face_up, :boolean, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :game_id,
          references(:games,
            column: :id,
            name: "game_cards_game_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :user_id,
          references(:users,
            column: :id,
            name: "game_cards_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :card_id,
          references(:cards,
            column: :id,
            name: "game_cards_card_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:game_cards, "game_cards_game_id_fkey")

    drop constraint(:game_cards, "game_cards_user_id_fkey")

    drop constraint(:game_cards, "game_cards_card_id_fkey")

    drop table(:game_cards)
  end
end
