defmodule Sanctum.Repo.Migrations.UpdateHealthPerHero do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute "ALTER TABLE cards ALTER COLUMN health_per_hero TYPE boolean USING false"
    execute "ALTER TABLE cards ALTER COLUMN health_per_hero SET DEFAULT false"
  end

  def down do
    alter table(:cards) do
      modify :health_per_hero, :bigint, default: nil
    end
  end
end
