defmodule Sanctum.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:game_schemes) do
      modify :counter, :bigint, null: false
      modify :threat, :bigint, null: false
    end
  end

  def down do
    alter table(:game_schemes) do
      modify :threat, :bigint, null: true
      modify :counter, :bigint, null: true
    end
  end
end
