defmodule Sanctum.Repo.Migrations.AllowNilCardImages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:cards) do
      modify :image_url, :text, null: true
    end
  end

  def down do
    alter table(:cards) do
      modify :image_url, :text, null: false
    end
  end
end
