defmodule Sanctum.Repo.Migrations.ExpandScenarioSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:scenarios) do
      add :name, :text, null: false
      add :set, :text, null: false
    end
  end

  def down do
    alter table(:scenarios) do
      remove :set
      remove :name
    end
  end
end
