defmodule Sanctum.Repo.Migrations.RemoveHandsizeFromGamePlayer do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:game_players) do
      remove :hand_size
    end
  end

  def down do
    alter table(:game_players) do
      add :hand_size, :bigint
    end
  end
end
