defmodule Sanctum.Repo.Migrations.ModifyGameVillians do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:game_villians) do
      add :card_id,
          references(:cards,
            column: :id,
            name: "game_villians_card_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:game_villians, "game_villians_card_id_fkey")

    alter table(:game_villians) do
      remove :card_id
    end
  end
end
