defmodule Sanctum.Repo.Migrations.MigrateResources5 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:cards) do
      add :is_multi_sided, :boolean, default: false
      add :permanent, :boolean, default: false
    end
  end

  def down do
    alter table(:cards) do
      remove :permanent
      remove :is_multi_sided
    end
  end
end
