defmodule Sanctum.Repo.Migrations.AddPackToCards do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:cards), :card_set, to: :set

    alter table(:cards) do
      add :pack, :text
    end
  end

  def down do
    alter table(:cards) do
      remove :pack
    end

    rename table(:cards), :set, to: :card_set
  end
end
