defmodule Sanctum.Repo.Migrations.AddUserToGamePlayer do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:game_players) do
      add :user_id,
          references(:users,
            column: :id,
            name: "game_players_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:game_players, "game_players_user_id_fkey")

    alter table(:game_players) do
      remove :user_id
    end
  end
end
