defmodule Sanctum.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:villains) do
      modify :set, :text, null: false
      modify :villain_name, :text, null: false
    end
  end

  def down do
    alter table(:villains) do
      modify :villain_name, :text, null: true
      modify :set, :text, null: true
    end
  end
end
