defmodule Sanctum.Repo.Migrations.AddTokensToGameCards do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:game_cards) do
      add :threat, :bigint, default: 0
      add :damage, :bigint, default: 0
      add :counter, :bigint, default: 0
    end
  end

  def down do
    alter table(:game_cards) do
      remove :counter
      remove :damage
      remove :threat
    end
  end
end
