defmodule Sanctum.Repo.Migrations.MigrateResources4 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:cards) do
      remove :image_url
      remove :boost_star
      remove :boost
      remove :max_threat
      remove :escalation_threat
      remove :base_threat
      remove :scheme
      remove :stage
      remove :health_per_hero
      remove :recover
      remove :hand_size
      remove :resource_wild_count
      remove :resource_mental_count
      remove :resource_physical_count
      remove :resource_energy_count
      remove :hazard_icon
      remove :crisis_icon
      remove :amplify_icon
      remove :acceleration_icon
    end
  end

  def down do
    alter table(:cards) do
      add :acceleration_icon, :boolean, default: false
      add :amplify_icon, :boolean, default: false
      add :crisis_icon, :boolean, default: false
      add :hazard_icon, :boolean, default: false
      add :resource_energy_count, :bigint
      add :resource_physical_count, :bigint
      add :resource_mental_count, :bigint
      add :resource_wild_count, :bigint
      add :hand_size, :bigint
      add :recover, :bigint
      add :health_per_hero, :boolean, default: false
      add :stage, :bigint
      add :scheme, :bigint
      add :base_threat, :bigint
      add :escalation_threat, :bigint
      add :max_threat, :bigint
      add :boost, :bigint
      add :boost_star, :boolean, default: false
      add :image_url, :text
    end
  end
end
