defmodule Sanctum.Repo.Migrations.AddUniqueScenarioSetIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:scenarios, [:set], name: "scenarios_unique_set_index")
  end

  def down do
    drop_if_exists unique_index(:scenarios, [:set], name: "scenarios_unique_set_index")
  end
end
