defmodule Sanctum.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:cards) do
      remove :permanent
      remove :cost
      remove :health
      remove :defense_cost
      remove :defense
      remove :thwart_cost
      remove :thwart
      remove :attack_cost
      remove :attack
      remove :text
    end
  end

  def down do
    alter table(:cards) do
      add :text, :text
      add :attack, :bigint
      add :attack_cost, :bigint
      add :thwart, :bigint
      add :thwart_cost, :bigint
      add :defense, :bigint
      add :defense_cost, :bigint
      add :health, :bigint
      add :cost, :bigint
      add :permanent, :boolean, default: false
    end
  end
end
