defmodule Sanctum.Repo.Migrations.AddHeroes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:heroes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :hero_name, :text
      add :alter_ego_name, :text
      add :set, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :hero_card_id,
          references(:cards,
            column: :id,
            name: "heroes_hero_card_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :alter_ego_card_id,
          references(:cards,
            column: :id,
            name: "heroes_alter_ego_card_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:cards, [:set])
  end

  def down do
    drop_if_exists index(:cards, [:set])

    drop constraint(:heroes, "heroes_hero_card_id_fkey")

    drop constraint(:heroes, "heroes_alter_ego_card_id_fkey")

    drop table(:heroes)
  end
end
