defmodule Sanctum.Repo.Migrations.AddCardSides do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:heroes) do
      remove :alter_ego_card_id
      remove :hero_card_id
    end

    create table(:card_sides, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :side_identifier, :text, null: false
      add :is_primary_side, :boolean, default: false
      add :code, :text, null: false
      add :name, :text, null: false
      add :subname, :text
      add :traits, {:array, :text}, default: []
      add :type, :text
      add :aspect, :text
      add :text, :text
      add :attack, :bigint
      add :attack_cost, :bigint
      add :thwart, :bigint
      add :thwart_cost, :bigint
      add :defense, :bigint
      add :defense_cost, :bigint
      add :health, :bigint
      add :cost, :bigint
      add :deck_limit, :bigint
      add :unique, :boolean, default: false
      add :permanent, :boolean, default: false
      add :acceleration_icon, :boolean, default: false
      add :amplify_icon, :boolean, default: false
      add :crisis_icon, :boolean, default: false
      add :hazard_icon, :boolean, default: false
      add :resource_energy_count, :bigint
      add :resource_physical_count, :bigint
      add :resource_mental_count, :bigint
      add :resource_wild_count, :bigint
      add :hand_size, :bigint
      add :recover, :bigint
      add :health_per_hero, :boolean, default: false
      add :stage, :bigint
      add :scheme, :bigint
      add :base_threat, :bigint
      add :escalation_threat, :bigint
      add :max_threat, :bigint
      add :boost, :bigint
      add :boost_star, :boolean, default: false
      add :image_url, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :card_id,
          references(:cards,
            column: :id,
            name: "card_sides_card_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:card_sides, [:card_id, :side_identifier],
             name: "card_sides_unique_card_side_index"
           )

    create unique_index(:card_sides, [:code], name: "card_sides_unique_code_index")
  end

  def down do
    drop_if_exists unique_index(:card_sides, [:code], name: "card_sides_unique_code_index")

    drop_if_exists unique_index(:card_sides, [:card_id, :side_identifier],
                     name: "card_sides_unique_card_side_index"
                   )

    drop constraint(:card_sides, "card_sides_card_id_fkey")

    drop table(:card_sides)

    alter table(:heroes) do
      add :hero_card_id,
          references(:cards,
            column: :id,
            name: "heroes_hero_card_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :alter_ego_card_id,
          references(:cards,
            column: :id,
            name: "heroes_alter_ego_card_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end
end
