defmodule Sanctum.Repo.Migrations.AddImageUrlToCards do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:cards) do
      add :image_url, :text, null: false
    end
  end

  def down do
    alter table(:cards) do
      remove :image_url
    end
  end
end
