defmodule Sanctum.Repo.Migrations.AddUserApiKeys do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_api_keys, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :provider, :text, null: false, default: "anthropic"
      add :key_hint, :text, null: false
      add :last_validated_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "user_api_keys_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :encrypted_key, :binary, null: false
    end

    create unique_index(:user_api_keys, [:user_id, :provider],
             name: "user_api_keys_unique_user_provider_index"
           )
  end

  def down do
    drop constraint(:user_api_keys, "user_api_keys_user_id_fkey")

    drop_if_exists unique_index(:user_api_keys, [:user_id, :provider],
                     name: "user_api_keys_unique_user_provider_index"
                   )

    drop table(:user_api_keys)
  end
end
