defmodule Sanctum.Repo.Migrations.AddDeckPopularity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:decks) do
      add :favorite_count, :bigint, null: false, default: 0
    end

    create index(
             :decks,
             [
               "(mcdb_like_count + favorite_count) DESC",
               "(COALESCE(mcdb_date_update, updated_at)) DESC"
             ],
             name: "decks_popularity_index"
           )

    execute("""
    CREATE OR REPLACE FUNCTION deck_favorites_count_trigger() RETURNS trigger AS $$
    BEGIN
      IF TG_OP = 'INSERT' THEN
        UPDATE decks SET favorite_count = favorite_count + 1 WHERE id = NEW.deck_id;
        RETURN NEW;
      ELSE
        UPDATE decks SET favorite_count = GREATEST(favorite_count - 1, 0) WHERE id = OLD.deck_id;
        RETURN OLD;
      END IF;
    END;
    $$ LANGUAGE plpgsql;
    """)

    execute("""
    CREATE TRIGGER deck_favorites_count
    AFTER INSERT OR DELETE ON deck_favorites
    FOR EACH ROW EXECUTE FUNCTION deck_favorites_count_trigger();
    """)

    execute("""
    UPDATE decks d SET favorite_count = f.n
    FROM (SELECT deck_id, count(*) AS n FROM deck_favorites GROUP BY deck_id) f
    WHERE d.id = f.deck_id;
    """)
  end

  def down do
    execute("""
    SELECT 1;
    """)

    execute("""
    DROP TRIGGER IF EXISTS deck_favorites_count ON deck_favorites;
    """)

    execute("""
    DROP FUNCTION IF EXISTS deck_favorites_count_trigger();
    """)

    drop_if_exists index(
                     :decks,
                     [
                       "(mcdb_like_count + favorite_count) DESC",
                       "(COALESCE(mcdb_date_update, updated_at)) DESC"
                     ],
                     name: "decks_popularity_index"
                   )

    alter table(:decks) do
      remove :favorite_count
    end
  end
end
