defmodule Sanctum.Repo.Migrations.DeckVisibilityState do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:decks) do
      add :visibility, :text, null: false, default: "published"
      add :state, :text, null: false, default: "final"
    end
  end

  def down do
    alter table(:decks) do
      remove :state
      remove :visibility
    end
  end
end
