defmodule Sanctum.Repo.Migrations.AddDeckBrowseIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:decks, ["uniqueness_percentile DESC NULLS LAST"],
             name: "decks_uniqueness_percentile_index"
           )

    create index(:decks, [:aspects], using: "GIN")

    create index(:decks, [:title])

    create index(:decks, [:updated_at])

    create index(:decks, [:hero_id])
  end

  def down do
    drop_if_exists index(:decks, [:hero_id])

    drop_if_exists index(:decks, [:updated_at])

    drop_if_exists index(:decks, [:title])

    drop_if_exists index(:decks, [:aspects])

    drop_if_exists index(:decks, ["uniqueness_percentile DESC NULLS LAST"],
                     name: "decks_uniqueness_percentile_index"
                   )
  end
end
