defmodule Sanctum.Repo.Migrations.AddDeckFavorites do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:deck_favorites, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "deck_favorites_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :deck_id,
          references(:decks,
            column: :id,
            name: "deck_favorites_deck_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:deck_favorites, [:user_id])

    create unique_index(:deck_favorites, [:user_id, :deck_id],
             name: "deck_favorites_unique_user_deck_index"
           )
  end

  def down do
    drop constraint(:deck_favorites, "deck_favorites_user_id_fkey")

    drop constraint(:deck_favorites, "deck_favorites_deck_id_fkey")

    drop_if_exists unique_index(:deck_favorites, [:user_id, :deck_id],
                     name: "deck_favorites_unique_user_deck_index"
                   )

    drop_if_exists index(:deck_favorites, [:user_id])

    drop table(:deck_favorites)
  end
end
