defmodule Sanctum.Repo.Migrations.AddEventsDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :status, :text, null: false, default: "setup"
      add :time_limit_minutes, :bigint, null: false, default: 180
      add :started_at, :utc_datetime
      add :loki_hp, :bigint
      add :loki_flipped, :boolean, null: false, default: false
      add :worlds_collide_threat, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "events_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:event_pods, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :mangog_active, :boolean, null: false, default: false
      add :mangog_hp, :bigint, null: false, default: 10
      add :door_active, :boolean, null: false, default: false
      add :door_threat, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :event_id,
          references(:events,
            column: :id,
            name: "event_pods_event_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false
    end

    create table(:event_groups, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :player_count, :bigint, null: false, default: 1
      add :difficulty, :text, null: false, default: "standard"
      add :status, :text, null: false, default: "playing"
      add :players_defeated, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :pod_id,
          references(:event_pods,
            column: :id,
            name: "event_groups_pod_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false
    end
  end

  def down do
    drop constraint(:event_groups, "event_groups_pod_id_fkey")

    drop table(:event_groups)

    drop constraint(:event_pods, "event_pods_event_id_fkey")

    drop table(:event_pods)

    drop constraint(:events, "events_user_id_fkey")

    drop table(:events)
  end
end
