defmodule Sanctum.Repo.Migrations.AddCardSideFlavor do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:card_sides) do
      add :flavor, :text
    end
  end

  def down do
    alter table(:card_sides) do
      remove :flavor
    end
  end
end
