defmodule Sanctum.Repo.Migrations.MoveMangogDoorToGroup do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:event_pods) do
      remove :door_threat
      remove :door_active
      remove :mangog_hp
      remove :mangog_active
    end

    alter table(:event_groups) do
      add :mangog_active, :boolean, null: false, default: false
      add :mangog_hp, :bigint, null: false, default: 0
      add :door_active, :boolean, null: false, default: false
      add :door_threat, :bigint, null: false, default: 0
    end
  end

  def down do
    alter table(:event_groups) do
      remove :door_threat
      remove :door_active
      remove :mangog_hp
      remove :mangog_active
    end

    alter table(:event_pods) do
      add :mangog_active, :boolean, null: false, default: false
      add :mangog_hp, :bigint, null: false, default: 10
      add :door_active, :boolean, null: false, default: false
      add :door_threat, :bigint, null: false, default: 0
    end
  end
end
