defmodule Sanctum.Repo.Migrations.DropStatCostColumns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:card_sides) do
      remove :defense_cost
      remove :thwart_cost
      remove :attack_cost
    end
  end

  def down do
    alter table(:card_sides) do
      add :attack_cost, :bigint
      add :thwart_cost, :bigint
      add :defense_cost, :bigint
    end
  end
end
