defmodule Sanctum.Repo.Migrations.RequireHomebrewSetOnCustomContent do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create constraint(:aspects, :aspects_origin_set_consistency,
             check: """
               (origin = 'official') = (homebrew_set_id IS NULL)
             """
           )

    create constraint(:cards, :cards_origin_set_consistency,
             check: """
               (origin = 'official') = (homebrew_set_id IS NULL)
             """
           )

    create constraint(:card_alts, :card_alts_origin_set_consistency,
             check: """
               (origin = 'official') = (homebrew_set_id IS NULL)
             """
           )
  end

  def down do
    drop_if_exists constraint(:card_alts, :card_alts_origin_set_consistency)

    drop_if_exists constraint(:cards, :cards_origin_set_consistency)

    drop_if_exists constraint(:aspects, :aspects_origin_set_consistency)
  end
end
