defmodule Sanctum.Repo.Migrations.AddDeckMcdbDates do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:decks) do
      add :mcdb_date_creation, :utc_datetime
      add :mcdb_date_update, :utc_datetime
    end
  end

  def down do
    alter table(:decks) do
      remove :mcdb_date_update
      remove :mcdb_date_creation
    end
  end
end
