defmodule Sanctum.Repo.Migrations.RenameGameVillainActiveStageFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:game_villains) do
      remove :active_stage_side_id
      remove :active_stage_card_id

      add :card_id,
          references(:cards,
            column: :id,
            name: "game_villains_card_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :active_side_id,
          references(:card_sides,
            column: :id,
            name: "game_villains_active_side_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:game_villains, "game_villains_card_id_fkey")

    drop constraint(:game_villains, "game_villains_active_side_id_fkey")

    alter table(:game_villains) do
      remove :active_side_id
      remove :card_id

      add :active_stage_card_id,
          references(:cards,
            column: :id,
            name: "game_villains_active_stage_card_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :active_stage_side_id,
          references(:card_sides,
            column: :id,
            name: "game_villains_active_stage_side_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end
end
