defmodule Sanctum.Repo.Migrations.AddCustomAltArt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:card_alts) do
      add :origin, :text, null: false, default: "official"
      add :artist, :text

      add :creator_id,
          references(:users,
            column: :id,
            name: "card_alts_creator_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )

      add :homebrew_project_id,
          references(:homebrew_projects,
            column: :id,
            name: "card_alts_homebrew_project_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end

    create index(:card_alts, [:creator_id])

    create index(:card_alts, [:homebrew_project_id])

    create constraint(:card_alts, :card_alts_origin_consistency,
             check: """
               (origin = 'official') = (homebrew_project_id IS NULL) AND (origin = 'official') = (creator_id IS NULL)
             """
           )
  end

  def down do
    drop_if_exists constraint(:card_alts, :card_alts_origin_consistency)

    drop_if_exists index(:card_alts, [:homebrew_project_id])

    drop_if_exists index(:card_alts, [:creator_id])

    drop constraint(:card_alts, "card_alts_creator_id_fkey")

    drop constraint(:card_alts, "card_alts_homebrew_project_id_fkey")

    alter table(:card_alts) do
      remove :homebrew_project_id
      remove :creator_id
      remove :artist
      remove :origin
    end
  end
end
