defmodule Sanctum.Repo.Migrations.AddHomebrewSets do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:homebrew_sets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :slug, :text
      add :description, :text
      add :banner_url, :text
      add :visibility, :text, null: false, default: "private"
      add :maturity, :text, null: false, default: "draft"
      add :tags, {:array, :text}, default: []
      add :attestation, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :homebrew_project_id,
          references(:homebrew_projects,
            column: :id,
            name: "homebrew_sets_homebrew_project_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :creator_id,
          references(:users,
            column: :id,
            name: "homebrew_sets_creator_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :set_kind_id,
          references(:set_kinds,
            column: :id,
            name: "homebrew_sets_set_kind_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :parent_set_id,
          references(:homebrew_sets,
            column: :id,
            name: "homebrew_sets_parent_set_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end

    create index(:homebrew_sets, [:homebrew_project_id])

    create index(:homebrew_sets, [:creator_id])

    create index(:homebrew_sets, [:parent_set_id])
  end

  def down do
    drop_if_exists index(:homebrew_sets, [:parent_set_id])

    drop_if_exists index(:homebrew_sets, [:creator_id])

    drop_if_exists index(:homebrew_sets, [:homebrew_project_id])

    drop constraint(:homebrew_sets, "homebrew_sets_parent_set_id_fkey")

    drop constraint(:homebrew_sets, "homebrew_sets_set_kind_id_fkey")

    drop constraint(:homebrew_sets, "homebrew_sets_creator_id_fkey")

    drop constraint(:homebrew_sets, "homebrew_sets_homebrew_project_id_fkey")

    drop table(:homebrew_sets)
  end
end
