defmodule Sanctum.Repo.Migrations.SplitCardFaction do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:card_sides) do
      add :ownership, :text
    end
  end

  def down do
    alter table(:card_sides) do
      remove :ownership
    end
  end
end
