defmodule Sanctum.Repo.Migrations.AddGameCardGameId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:game_cards) do
      add :game_id,
          references(:games,
            column: :id,
            name: "game_cards_game_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          )
    end
  end

  def down do
    drop constraint(:game_cards, "game_cards_game_id_fkey")

    alter table(:game_cards) do
      remove :game_id
    end
  end
end
