defmodule Sanctum.Repo.Migrations.AddDecksNewestAtIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:decks, ["(COALESCE(mcdb_date_update, updated_at)) DESC"],
             name: "decks_newest_at_index"
           )
  end

  def down do
    drop_if_exists index(:decks, ["(COALESCE(mcdb_date_update, updated_at)) DESC"],
                     name: "decks_newest_at_index"
                   )
  end
end
