defmodule Sanctum.Repo.Migrations.AddHeroColors do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:heroes) do
      add :colors, {:array, :text}
      add :primary_color, :text
      add :secondary_color, :text
    end
  end

  def down do
    alter table(:heroes) do
      remove :secondary_color
      remove :primary_color
      remove :colors
    end
  end
end
