defmodule Sanctum.Repo.Migrations.AddGameLog do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:logged_games, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :played_at, :date, null: false, default: fragment("CURRENT_DATE")
      add :modular_sets, {:array, :text}, null: false, default: []

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "logged_games_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :scenario_id,
          references(:scenarios,
            column: :id,
            name: "logged_games_scenario_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :villain_id,
          references(:villains,
            column: :id,
            name: "logged_games_villain_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :main_scheme_id,
          references(:cards,
            column: :id,
            name: "logged_games_main_scheme_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:logged_game_players, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :aspect,
          references(:aspects,
            column: :key,
            name: "logged_game_players_aspect_fkey",
            type: :text,
            prefix: "public"
          )

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :logged_game_id,
          references(:logged_games,
            column: :id,
            name: "logged_game_players_logged_game_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :hero_id,
          references(:heroes,
            column: :id,
            name: "logged_game_players_hero_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:logged_game_players, "logged_game_players_hero_id_fkey")

    drop constraint(:logged_game_players, "logged_game_players_logged_game_id_fkey")

    drop constraint(:logged_game_players, "logged_game_players_aspect_fkey")

    drop table(:logged_game_players)

    drop constraint(:logged_games, "logged_games_main_scheme_id_fkey")

    drop constraint(:logged_games, "logged_games_villain_id_fkey")

    drop constraint(:logged_games, "logged_games_scenario_id_fkey")

    drop constraint(:logged_games, "logged_games_user_id_fkey")

    drop table(:logged_games)
  end
end
