defmodule Sanctum.Repo.Migrations.ScenarioModularSets do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:scenario_modular_sets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :scenario_id,
          references(:scenarios,
            column: :id,
            name: "scenario_modular_sets_scenario_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :card_set_id,
          references(:card_sets,
            column: :id,
            name: "scenario_modular_sets_card_set_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:scenario_modular_sets, [:scenario_id, :card_set_id],
             name: "scenario_modular_sets_unique_scenario_card_set_index"
           )

    alter table(:scenarios) do
      remove :recommended_modular_sets
    end
  end

  def down do
    alter table(:scenarios) do
      add :recommended_modular_sets, {:array, :text}, null: false
    end

    drop constraint(:scenario_modular_sets, "scenario_modular_sets_card_set_id_fkey")

    drop constraint(:scenario_modular_sets, "scenario_modular_sets_scenario_id_fkey")

    drop_if_exists unique_index(:scenario_modular_sets, [:scenario_id, :card_set_id],
                     name: "scenario_modular_sets_unique_scenario_card_set_index"
                   )

    drop table(:scenario_modular_sets)
  end
end
