defmodule Sanctum.Repo.Migrations.DropGroupPlayersDefeated do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:event_groups) do
      remove :players_defeated
    end
  end

  def down do
    alter table(:event_groups) do
      add :players_defeated, :bigint, null: false, default: 0
    end
  end
end
