defmodule Sanctum.Repo.Migrations.AddAvatarSource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :avatar_source, :text, null: false, default: "provider"
      add :provider_avatar_url, :text
    end
  end

  def down do
    alter table(:users) do
      remove :provider_avatar_url
      remove :avatar_source
    end
  end
end
