defmodule Sanctum.Repo.Migrations.AddHomebrewProjectsAndCardOrigin do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:homebrew_projects, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :banner_url, :text
      add :content_types, {:array, :text}, default: []
      add :maturity, :text, null: false, default: "draft"
      add :visibility, :text, null: false, default: "private"
      add :tags, {:array, :text}, default: []
      add :attestation, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :creator_id,
          references(:users,
            column: :id,
            name: "homebrew_projects_creator_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    alter table(:cards) do
      add :origin, :text, null: false, default: "official"

      add :homebrew_project_id,
          references(:homebrew_projects,
            column: :id,
            name: "cards_homebrew_project_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end

    create index(:cards, [:homebrew_project_id])

    drop constraint(:card_sides, "card_sides_card_id_fkey")

    alter table(:card_sides) do
      modify :card_id,
             references(:cards,
               column: :id,
               name: "card_sides_card_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create constraint(:cards, :cards_origin_project_consistency,
             check: """
               (origin = 'official') = (homebrew_project_id IS NULL)
             """
           )
  end

  def down do
    drop_if_exists constraint(:cards, :cards_origin_project_consistency)

    drop constraint(:card_sides, "card_sides_card_id_fkey")

    alter table(:card_sides) do
      modify :card_id,
             references(:cards,
               column: :id,
               name: "card_sides_card_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:cards, [:homebrew_project_id])

    drop constraint(:cards, "cards_homebrew_project_id_fkey")

    alter table(:cards) do
      remove :homebrew_project_id
      remove :origin
    end

    drop constraint(:homebrew_projects, "homebrew_projects_creator_id_fkey")

    drop table(:homebrew_projects)
  end
end
