defmodule Sanctum.Repo.Migrations.AddGameReferentialIntegrity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:game_villains, "game_villains_game_id_fkey")

    alter table(:game_villains) do
      modify :game_id,
             references(:games,
               column: :id,
               name: "game_villains_game_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end

    drop constraint(:game_schemes, "game_schemes_game_id_fkey")

    alter table(:game_schemes) do
      modify :counter, :bigint, null: false
      modify :threat, :bigint, null: false, default: 0

      modify :game_id,
             references(:games,
               column: :id,
               name: "game_schemes_game_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end

    drop constraint(:game_players, "game_players_game_id_fkey")

    alter table(:game_players) do
      modify :game_id,
             references(:games,
               column: :id,
               name: "game_players_game_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end

    drop constraint(:game_encounter_decks, "game_encounter_decks_game_id_fkey")

    alter table(:game_encounter_decks) do
      modify :game_id,
             references(:games,
               column: :id,
               name: "game_encounter_decks_game_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end

    create index(:game_cards, [:game_encounter_deck_id, :zone])

    create index(:game_cards, [:game_player_id, :zone])

    create index(:game_cards, [:game_encounter_deck_id])

    create index(:game_cards, [:game_player_id])

    drop constraint(:game_cards, "game_cards_game_encounter_deck_id_fkey")

    drop constraint(:game_cards, "game_cards_game_player_id_fkey")

    alter table(:game_cards) do
      modify :game_player_id,
             references(:game_players,
               column: :id,
               name: "game_cards_game_player_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )

      modify :game_encounter_deck_id,
             references(:game_encounter_decks,
               column: :id,
               name: "game_cards_game_encounter_deck_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end
  end

  def down do
    drop constraint(:game_cards, "game_cards_game_player_id_fkey")

    drop constraint(:game_cards, "game_cards_game_encounter_deck_id_fkey")

    alter table(:game_cards) do
      modify :game_encounter_deck_id,
             references(:game_encounter_decks,
               column: :id,
               name: "game_cards_game_encounter_deck_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :game_player_id,
             references(:game_players,
               column: :id,
               name: "game_cards_game_player_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:game_cards, [:game_player_id])

    drop_if_exists index(:game_cards, [:game_encounter_deck_id])

    drop_if_exists index(:game_cards, [:game_player_id, :zone])

    drop_if_exists index(:game_cards, [:game_encounter_deck_id, :zone])

    drop constraint(:game_encounter_decks, "game_encounter_decks_game_id_fkey")

    alter table(:game_encounter_decks) do
      modify :game_id,
             references(:games,
               column: :id,
               name: "game_encounter_decks_game_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:game_players, "game_players_game_id_fkey")

    alter table(:game_players) do
      modify :game_id,
             references(:games,
               column: :id,
               name: "game_players_game_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:game_schemes, "game_schemes_game_id_fkey")

    alter table(:game_schemes) do
      modify :game_id,
             references(:games,
               column: :id,
               name: "game_schemes_game_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :threat, :bigint, null: true, default: nil
      modify :counter, :bigint, null: true
    end

    drop constraint(:game_villains, "game_villains_game_id_fkey")

    alter table(:game_villains) do
      modify :game_id,
             references(:games,
               column: :id,
               name: "game_villains_game_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
