defmodule Sanctum.Repo.Migrations.AddMcdbCredentials do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:mcdb_credentials, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :expires_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "mcdb_credentials_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :encrypted_access_token, :binary, null: false
      add :encrypted_refresh_token, :binary
    end

    create unique_index(:mcdb_credentials, [:user_id], name: "mcdb_credentials_unique_user_index")
  end

  def down do
    drop constraint(:mcdb_credentials, "mcdb_credentials_user_id_fkey")

    drop_if_exists unique_index(:mcdb_credentials, [:user_id],
                     name: "mcdb_credentials_unique_user_index"
                   )

    drop table(:mcdb_credentials)
  end
end
