defmodule Sanctum.Repo.Migrations.CreateAspectResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:aspects, primary_key: false) do
      add :key, :text, null: false, primary_key: true
      add :label, :text, null: false
      add :color, :text, null: false
      add :sort_order, :bigint, null: false, default: 100
      add :origin, :text, null: false, default: "official"
      add :deck_selectable, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :homebrew_project_id,
          references(:homebrew_projects,
            column: :id,
            name: "aspects_homebrew_project_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end

    create index(:aspects, [:homebrew_project_id])
  end

  def down do
    drop_if_exists index(:aspects, [:homebrew_project_id])

    drop constraint(:aspects, "aspects_homebrew_project_id_fkey")

    drop table(:aspects)
  end
end
