defmodule Sanctum.Repo.Migrations.AddCardSideSchemeStar do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:card_sides) do
      add :scheme_star, :boolean, default: false
    end
  end

  def down do
    alter table(:card_sides) do
      remove :scheme_star
    end
  end
end
