defmodule Sanctum.Repo.Migrations.AddDeckSyncModel do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:mcdb_users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :mcdb_user_id, :bigint, null: false
      add :username, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :sanctum_user_id,
          references(:users,
            column: :id,
            name: "mcdb_users_sanctum_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:mcdb_users, [:mcdb_user_id],
             name: "mcdb_users_unique_mcdb_user_id_index"
           )

    alter table(:decks) do
      add :source, :text, null: false, default: "native"
      add :mcdb_type, :text
      add :aspects, {:array, :text}, default: []
      add :meta, :map
      add :tags, :text
      add :description_md, :text
      add :version, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id,
          references(:users,
            column: :id,
            name: "decks_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :mcdb_user_id,
          references(:mcdb_users,
            column: :id,
            name: "decks_mcdb_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    drop_if_exists unique_index(:decks, [:mcdb_id], name: "decks_unique_mcdb_id_index")

    create unique_index(:decks, [:mcdb_type, :mcdb_id], name: "decks_unique_mcdb_deck_index")

    alter table(:deck_cards) do
      add :quantity, :bigint, null: false, default: 1
      add :ignore_deck_limit, :boolean, null: false, default: false
    end

    create unique_index(:deck_cards, [:deck_id, :card_id],
             name: "deck_cards_unique_deck_card_index"
           )
  end

  def down do
    drop_if_exists unique_index(:deck_cards, [:deck_id, :card_id],
                     name: "deck_cards_unique_deck_card_index"
                   )

    alter table(:deck_cards) do
      remove :ignore_deck_limit
      remove :quantity
    end

    drop constraint(:decks, "decks_owner_id_fkey")

    drop constraint(:decks, "decks_mcdb_user_id_fkey")

    drop_if_exists unique_index(:decks, [:mcdb_type, :mcdb_id],
                     name: "decks_unique_mcdb_deck_index"
                   )

    create unique_index(:decks, [:mcdb_id], name: "decks_unique_mcdb_id_index")

    alter table(:decks) do
      remove :mcdb_user_id
      remove :owner_id
      remove :updated_at
      remove :inserted_at
      remove :version
      remove :description_md
      remove :tags
      remove :meta
      remove :aspects
      remove :mcdb_type
      remove :source
    end

    drop constraint(:mcdb_users, "mcdb_users_sanctum_user_id_fkey")

    drop_if_exists unique_index(:mcdb_users, [:mcdb_user_id],
                     name: "mcdb_users_unique_mcdb_user_id_index"
                   )

    drop table(:mcdb_users)
  end
end
