defmodule Sanctum.Repo.Migrations.AddStructuredCardStats do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:card_sides) do
      add :attack, :map
      add :thwart, :map
      add :defense, :map
      add :health, :map
      add :recover, :map
      add :base_threat, :map
      add :escalation_threat, :map
      add :max_threat, :map
    end
  end

  def down do
    alter table(:card_sides) do
      remove :max_threat
      remove :escalation_threat
      remove :base_threat
      remove :recover
      remove :health
      remove :defense
      remove :thwart
      remove :attack
    end
  end
end
