defmodule Sanctum.Repo.Migrations.AddCollections do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:collection_packs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "collection_packs_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :pack_id,
          references(:packs,
            column: :id,
            name: "collection_packs_pack_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:collection_packs, [:user_id, :pack_id],
             name: "collection_packs_unique_user_pack_index"
           )

    create table(:collection_cards, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :status, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "collection_cards_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :card_id,
          references(:cards,
            column: :id,
            name: "collection_cards_card_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:collection_cards, [:user_id, :card_id],
             name: "collection_cards_unique_user_card_index"
           )

    alter table(:card_alts) do
      add :pack_id,
          references(:packs,
            column: :id,
            name: "card_alts_pack_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:card_alts, [:pack_id])
  end

  def down do
    drop constraint(:card_alts, "card_alts_pack_id_fkey")

    drop_if_exists index(:card_alts, [:pack_id])

    alter table(:card_alts) do
      remove :pack_id
    end

    drop constraint(:collection_cards, "collection_cards_user_id_fkey")

    drop constraint(:collection_cards, "collection_cards_card_id_fkey")

    drop_if_exists unique_index(:collection_cards, [:user_id, :card_id],
                     name: "collection_cards_unique_user_card_index"
                   )

    drop table(:collection_cards)

    drop constraint(:collection_packs, "collection_packs_user_id_fkey")

    drop constraint(:collection_packs, "collection_packs_pack_id_fkey")

    drop_if_exists unique_index(:collection_packs, [:user_id, :pack_id],
                     name: "collection_packs_unique_user_pack_index"
                   )

    drop table(:collection_packs)
  end
end
