defmodule Sanctum.Repo.Migrations.AddScenarioDescription do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:scenarios) do
      add :description_md, :text
    end
  end

  def down do
    alter table(:scenarios) do
      remove :description_md
    end
  end
end
