defmodule Sanctum.Repo.Migrations.AddAspectDefFk do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:card_sides) do
      modify :aspect,
             references(:aspects,
               column: :key,
               name: "card_sides_aspect_fkey",
               type: :text,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    create index(:card_sides, [:aspect])
  end

  def down do
    drop_if_exists index(:card_sides, [:aspect])

    drop constraint(:card_sides, "card_sides_aspect_fkey")

    alter table(:card_sides) do
      modify :aspect, :text
    end
  end
end
