defmodule Sanctum.Repo.Migrations.AddCatalogTaxonomy do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop table(:modular_sets)

    create table(:waves, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :number, :bigint, null: false
      add :name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:waves, [:number], name: "waves_unique_number_index")

    create table(:packs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :code, :text, null: false
      add :name, :text
      add :position, :bigint
      add :released_on, :date
      add :known_count, :bigint
      add :total_count, :bigint
      add :marvelcdb_id, :bigint
      add :product_type, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :wave_id,
          references(:waves,
            column: :id,
            name: "packs_wave_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:packs, [:code], name: "packs_unique_code_index")

    alter table(:cards) do
      add :card_set_id, :uuid
      add :pack_id, :uuid
    end

    create index(:cards, [:pack_id])

    create index(:cards, [:card_set_id])

    create table(:card_sets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:cards) do
      modify :card_set_id,
             references(:card_sets,
               column: :id,
               name: "cards_card_set_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :pack_id,
             references(:packs,
               column: :id,
               name: "cards_pack_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:card_sets) do
      add :code, :text, null: false
      add :name, :text
      add :set_type, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :pack_id,
          references(:packs,
            column: :id,
            name: "card_sets_pack_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :hero_set_id,
          references(:card_sets,
            column: :id,
            name: "card_sets_hero_set_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:card_sets, [:hero_set_id])

    create index(:card_sets, [:pack_id])

    create unique_index(:card_sets, [:code], name: "card_sets_unique_code_index")
  end

  def down do
    drop constraint(:card_sets, "card_sets_pack_id_fkey")

    drop constraint(:card_sets, "card_sets_hero_set_id_fkey")

    drop_if_exists unique_index(:card_sets, [:code], name: "card_sets_unique_code_index")

    drop_if_exists index(:card_sets, [:pack_id])

    drop_if_exists index(:card_sets, [:hero_set_id])

    alter table(:card_sets) do
      remove :hero_set_id
      remove :pack_id
      remove :updated_at
      remove :inserted_at
      remove :set_type
      remove :name
      remove :code
    end

    drop constraint(:cards, "cards_card_set_id_fkey")

    drop constraint(:cards, "cards_pack_id_fkey")

    alter table(:cards) do
      modify :pack_id, :uuid
      modify :card_set_id, :uuid
    end

    drop table(:card_sets)

    drop_if_exists index(:cards, [:card_set_id])

    drop_if_exists index(:cards, [:pack_id])

    alter table(:cards) do
      remove :pack_id
      remove :card_set_id
    end

    drop constraint(:packs, "packs_wave_id_fkey")

    drop_if_exists unique_index(:packs, [:code], name: "packs_unique_code_index")

    drop table(:packs)

    drop_if_exists unique_index(:waves, [:number], name: "waves_unique_number_index")

    drop table(:waves)

    # Rollback would require recreating the table manually
  end
end
