defmodule Sanctum.Repo.Migrations.AddCardAlts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:card_alts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :code, :text, null: false
      add :base_code, :text, null: false
      add :side_identifier, :text
      add :pack, :text
      add :set, :text
      add :image_url, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :card_id,
          references(:cards,
            column: :id,
            name: "card_alts_card_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:card_alts, [:code], name: "card_alts_unique_alt_code_index")
  end

  def down do
    drop constraint(:card_alts, "card_alts_card_id_fkey")

    drop_if_exists unique_index(:card_alts, [:code], name: "card_alts_unique_alt_code_index")

    drop table(:card_alts)
  end
end
