defmodule Sanctum.Repo.Migrations.DropFlatCardStats do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:card_sides) do
      remove :max_threat
      remove :escalation_threat
      remove :base_threat
      remove :health_per_hero
      remove :recover
      remove :health
      remove :defense
      remove :thwart
      remove :attack
    end
  end

  def down do
    alter table(:card_sides) do
      add :attack, :bigint
      add :thwart, :bigint
      add :defense, :bigint
      add :health, :bigint
      add :recover, :bigint
      add :health_per_hero, :boolean, default: false
      add :base_threat, :bigint
      add :escalation_threat, :bigint
      add :max_threat, :bigint
    end
  end
end
