defmodule Sanctum.Repo.Migrations.AddDeckUniqueness do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:decks) do
      add :uniqueness_score, :float
      add :uniqueness_percentile, :bigint
      add :uniqueness_at, :utc_datetime
      add :nearest_deck_id, :uuid
    end
  end

  def down do
    alter table(:decks) do
      remove :nearest_deck_id
      remove :uniqueness_at
      remove :uniqueness_percentile
      remove :uniqueness_score
    end
  end
end
