defmodule Sanctum.Repo.Migrations.AddHomebrewSetFk do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:aspects) do
      add :homebrew_set_id,
          references(:homebrew_sets,
            column: :id,
            name: "aspects_homebrew_set_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end

    create index(:aspects, [:homebrew_set_id])

    alter table(:cards) do
      add :homebrew_set_id,
          references(:homebrew_sets,
            column: :id,
            name: "cards_homebrew_set_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end

    create index(:cards, [:homebrew_set_id])

    alter table(:card_alts) do
      add :homebrew_set_id,
          references(:homebrew_sets,
            column: :id,
            name: "card_alts_homebrew_set_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end

    create index(:card_alts, [:homebrew_set_id])
  end

  def down do
    drop_if_exists index(:card_alts, [:homebrew_set_id])

    drop constraint(:card_alts, "card_alts_homebrew_set_id_fkey")

    alter table(:card_alts) do
      remove :homebrew_set_id
    end

    drop_if_exists index(:cards, [:homebrew_set_id])

    drop constraint(:cards, "cards_homebrew_set_id_fkey")

    alter table(:cards) do
      remove :homebrew_set_id
    end

    drop_if_exists index(:aspects, [:homebrew_set_id])

    drop constraint(:aspects, "aspects_homebrew_set_id_fkey")

    alter table(:aspects) do
      remove :homebrew_set_id
    end
  end
end
