defmodule Sanctum.Repo.Migrations.MangogDoorLifecycleStatus do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:event_groups) do
      remove :door_active
      remove :mangog_active
      add :mangog_status, :text, null: false, default: "out"
      add :door_status, :text, null: false, default: "out"
    end
  end

  def down do
    alter table(:event_groups) do
      remove :door_status
      remove :mangog_status
      add :mangog_active, :boolean, null: false, default: false
      add :door_active, :boolean, null: false, default: false
    end
  end
end
