defmodule Sanctum.Repo.Migrations.AddSetKinds do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:set_kinds, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :key, :text, null: false
      add :label, :text, null: false
      add :sort_order, :bigint, null: false, default: 100
      add :origin, :text, null: false, default: "official"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :homebrew_project_id,
          references(:homebrew_projects,
            column: :id,
            name: "set_kinds_homebrew_project_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end

    create unique_index(:set_kinds, [:key, :homebrew_project_id],
             name: "set_kinds_unique_key_per_project_index",
             nulls_distinct: false
           )

    create index(:set_kinds, [:homebrew_project_id])

    create constraint(:set_kinds, :set_kinds_origin_consistency,
             check: """
               (origin = 'official') = (homebrew_project_id IS NULL)
             """
           )
  end

  def down do
    drop_if_exists constraint(:set_kinds, :set_kinds_origin_consistency)

    drop_if_exists index(:set_kinds, [:homebrew_project_id])

    drop constraint(:set_kinds, "set_kinds_homebrew_project_id_fkey")

    drop_if_exists unique_index(:set_kinds, [:key, :homebrew_project_id],
                     name: "set_kinds_unique_key_per_project_index"
                   )

    drop table(:set_kinds)
  end
end
