defmodule Sanctum.Repo.Migrations.AddHeroCardFk do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:heroes) do
      add :card_id,
          references(:cards,
            column: :id,
            name: "heroes_card_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:heroes, "heroes_card_id_fkey")

    alter table(:heroes) do
      remove :card_id
    end
  end
end
