defmodule Sanctum.Repo.Migrations.AddMcdbScrapeState do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:mcdb_scrape_state, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :singleton, :boolean, null: false, default: true
      add :status, :text
      add :sort, :text
      add :page, :bigint
      add :last_page, :bigint
      add :rows_seen, :bigint, null: false, default: 0
      add :matched, :bigint, null: false, default: 0
      add :unmatched, :bigint, null: false, default: 0
      add :users_updated, :bigint, null: false, default: 0
      add :started_at, :utc_datetime_usec
      add :finished_at, :utc_datetime_usec
      add :last_error, :text
      add :missing_count, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:mcdb_scrape_state, [:singleton],
             name: "mcdb_scrape_state_singleton_index"
           )
  end

  def down do
    drop_if_exists unique_index(:mcdb_scrape_state, [:singleton],
                     name: "mcdb_scrape_state_singleton_index"
                   )

    drop table(:mcdb_scrape_state)
  end
end
