defmodule Sanctum.Repo.Migrations.CatalogFieldCleanup do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:scenarios) do
      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    alter table(:card_sides) do
      remove :permanent
      remove :unique
      remove :deck_limit
    end
  end

  def down do
    alter table(:card_sides) do
      add :deck_limit, :bigint
      add :unique, :boolean, default: false
      add :permanent, :boolean, default: false
    end

    alter table(:scenarios) do
      remove :updated_at
      remove :inserted_at
    end
  end
end
