defmodule Sanctum.Repo.Migrations.AddDeckMcdbSocialFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:decks) do
      add :mcdb_like_count, :bigint, null: false, default: 0
      add :mcdb_social_synced_at, :utc_datetime
    end
  end

  def down do
    alter table(:decks) do
      remove :mcdb_social_synced_at
      remove :mcdb_like_count
    end
  end
end
