defmodule Sanctum.Repo.Migrations.DeckCardsCardIdIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:deck_cards, [:card_id])
  end

  def down do
    drop_if_exists index(:deck_cards, [:card_id])
  end
end
