defmodule Sanctum.Repo.Migrations.AddMcdbDeckRefreshSchedule do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:decks) do
      add :mcdb_like_changed_at, :utc_datetime
      add :mcdb_social_next_check_at, :utc_datetime
    end

    create index(:decks, [:mcdb_social_next_check_at],
             name: "decks_mcdb_social_next_check_at_index",
             where: "mcdb_social_next_check_at IS NOT NULL"
           )
  end

  def down do
    drop_if_exists index(:decks, [:mcdb_social_next_check_at],
                     name: "decks_mcdb_social_next_check_at_index"
                   )

    alter table(:decks) do
      remove :mcdb_social_next_check_at
      remove :mcdb_like_changed_at
    end
  end
end
