defmodule Sanctum.Repo.Migrations.AddDeckSyncState do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:deck_sync_state, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :last_synced_date, :date
      add :singleton, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:deck_sync_state, [:singleton], name: "deck_sync_state_singleton_index")
  end

  def down do
    drop_if_exists unique_index(:deck_sync_state, [:singleton],
                     name: "deck_sync_state_singleton_index"
                   )

    drop table(:deck_sync_state)
  end
end
