defmodule Sanctum.Repo.Migrations.ScenarioVillainSetAndOwner do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:games, "games_scenario_id_fkey")

    alter table(:games) do
      modify :scenario_id,
             references(:scenarios,
               column: :id,
               name: "games_scenario_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             ),
             null: true
    end

    drop_if_exists unique_index(:scenarios, [:set], name: "scenarios_unique_set_index")

    alter table(:scenarios) do
      add :villain_set_id,
          references(:card_sets,
            column: :id,
            name: "scenarios_villain_set_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :owner_id,
          references(:users,
            column: :id,
            name: "scenarios_owner_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create unique_index(:scenarios, [:villain_set_id],
             name: "scenarios_unique_official_villain_set_index",
             where: "(owner_id IS NULL)"
           )
  end

  def down do
    drop constraint(:scenarios, "scenarios_owner_id_fkey")

    drop constraint(:scenarios, "scenarios_villain_set_id_fkey")

    drop_if_exists unique_index(:scenarios, [:villain_set_id],
                     name: "scenarios_unique_official_villain_set_index"
                   )

    alter table(:scenarios) do
      remove :owner_id
      remove :villain_set_id
    end

    create unique_index(:scenarios, [:set], name: "scenarios_unique_set_index")

    drop constraint(:games, "games_scenario_id_fkey")

    alter table(:games) do
      modify :scenario_id,
             references(:scenarios,
               column: :id,
               name: "games_scenario_id_fkey",
               type: :uuid,
               prefix: "public"
             ),
             null: false
    end
  end
end
